server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: payments-platform

  # Database Configuration
  datasource:
    url: jdbc:h2:mem:paymentdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # JPA & Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Automatically creates/updates database tables based on Entities
    show-sql: true      # Console me SQL queries print karega (debugging ke liye)

  # Enable H2 Web Console to view database in browser
  h2:
    console:
      enabled: true
      path: /h2-console


jwt:
  # Secret key must be long and secure (at least 32 chars)
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  # Expiration time in milliseconds (86400000 ms = 1 day)
  expiration: 86400000